case_id_list:
    Re-50:
        ref_params:
            l_ref: 0.0560000
            v_ref: 96.450000
            p_ref: 1.00E+05
        sim_params:
            rho: 0.0010100
            mu: 0.0001100
            g: 981
            dt: 0.00004
        x_range:
            - 80
            - 400
        y_range:
            - 40
            - 182
    Re-50-v2:
        ref_params:
            l_ref: 0.0560000
            v_ref: 96.450000
            p_ref: 1.00E+05
        sim_params:
            rho: 0.0010100
            mu: 0.0001100
            g: 981
            dt: 0.00004
        x_range:
            - 80
            - 400
        y_range: 
            - 40
            - 182
    Re-99:
        ref_params:
            l_ref: 1.00E-01
            v_ref: 90.000000
            p_ref: 1.00E+05
        sim_params:
            rho: 0.0011100
            mu: 1.00E-04
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 350
        y_range: 
            - 10
            - 212
        SVD_mode:
            - 23 # u
            - 26 # v
            - 28 # w
        fitting: 
            # avoid the select the boundary points due to polynomial fitting
            boundary_num: # x, y, t
                - 10
                - 10
                - 10
            deg: 4
    Re-115:
        ref_params:
            l_ref: 0.1292739
            v_ref: 103.927955
            p_ref: 1.10E+05
        sim_params:
            rho: 0.0010293
            mu: 0.0001195
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 350
        y_range: 
            - 10
            - 212
    Re-122:
        ref_params:
            l_ref: 0.1484624
            v_ref: 101.410330
            p_ref: 1.20E+05
        sim_params:
            rho: 0.0011805
            mu: 0.0001449
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 350
        y_range: 
            - 10
            - 212
    Re-127:
        ref_params:
            l_ref: 0.1042044
            v_ref: 133.189746
            p_ref: 1.30E+05
        sim_params:
            rho: 0.0011288
            mu: 0.0001228
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 240
        y_range: 
            - 10
            - 210
    Re-136:
        ref_params:
            l_ref: 0.1200606
            v_ref: 141.274400
            p_ref: 1.40E+05
        sim_params:
            rho: 0.0011835
            mu: 0.0001467
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 200
        y_range: 
            - 80
            - 142
    Re-148:
        ref_params:
            l_ref: 0.1138599
            v_ref: 148.219933
            p_ref: 1.50E+05
        sim_params:
            rho: 0.0010809
            mu: 0.0001230
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 400
        y_range: 
            - 10
            - 212
    Re-165:
        ref_params:
            l_ref: 0.1040628
            v_ref: 114.886347
            p_ref: 1.00E+06
        sim_params:
            rho: 0.0013437
            mu: 0.0000972
            g: 981
            dt: 0.00004
    Re-171:
        ref_params:
            l_ref: 0.1248002
            v_ref: 118.659712
            p_ref: 1.00E+06
        sim_params:
            rho: 0.0014805
            mu: 0.0001276
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 200
        y_range: 
            - 80
            - 142
    Re-185:
        ref_params:
            l_ref: 0.1080114
            v_ref: 169.894097
            p_ref: 1.10E+06
        sim_params:
            rho: 0.0012571
            mu: 0.0001242
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 200
        y_range: 
            - 80
            - 142
    Re-191:
        ref_params:
            l_ref: 0.1330436
            v_ref: 148.964530
            p_ref: 1.20E+06
        sim_params:
            rho: 0.0012075
            mu: 0.0001252
            g: 981
            dt: 0.00004
        x_range:
            - 100
            - 350
        y_range: 
            - 10
            - 212
        # x_range:
        #     - 120
        #     - 150
        # y_range: 
        #     - 10
        #     - 212
    # stage 2 data
    v2-Re-50:  
        ref_params:
            l_ref: 0.0850000
            v_ref: 68.000000
            p_ref: 1.00E+06
        sim_params:
            rho: 0.0010000
            mu: 0.0001156
            g: 981
            dt: 0.000004
        x_range:
        x_range:
            - 100
            - 490
        y_range:
            - 10
            - 212
        SVD_mode:
            - 3 # u
            - 4 # v
            - 4 # w
        fitting: 
            # avoid the select the boundary points due to polynomial fitting
            boundary_num: # x, y, t
                - 10
                - 10
                - 10
            deg: 4
    v2-Re-70:
        ref_params:
            l_ref: 0.0900000
            v_ref: 84.450000
            p_ref: 1.90E+05
        sim_params:
            rho: 0.0010500
            mu: 0.0001140
            g: 981
            dt: 0.000004
        x_range:
            - 120
            - 450
        y_range:
            - 20
            - 202
        # x_range:
        #     - 120
        #     - 450
        # y_range:
        #     - 20
        #     - 202
        SVD_mode:
            - 5 # u
            - 5 # v
            - 5 # w
        fitting:
            # avoid the select the boundary points due to polynomial fitting
            boundary_num: # x, y, t
                - 10
                - 10
                - 10
            deg: 4
            # boundary_num: # x, y, t
            #     - 5
            #     - 5
            #     - 5
            # deg: 3
    v2-Re-100:  # good
        ref_params:
            l_ref: 0.1000000
            v_ref: 100.000000
            p_ref: 1.80E+05
        sim_params:
            rho: 0.0011000
            mu: 0.0001100
            g: 981
            dt: 0.000004
        x_range:
            - 100
            - 480
        y_range: 
            - 10
            - 212
        SVD_mode:
            - 6 # u
            - 7 # v
            - 6 # w
        fitting: 
            # avoid the select the boundary points due to polynomial fitting
            boundary_num: # x, y, t
                - 5
                - 5
                - 5
            deg: 3
    v2-Re-150:
        ref_params:
            l_ref: 0.1050000
            v_ref: 135.200000
            p_ref: 1.50E+05
        sim_params:
            rho: 0.0011200
            mu: 0.0001060
            g: 981
            dt: 0.000004
        x_range:
            - 120
            - 180
        y_range: 
            - 10
            - 212
        SVD_mode:
            - 150 # u
            - 150 # v
            - 150 # w
        fitting: 
            # avoid the select the boundary points due to polynomial fitting
            boundary_num: # x, y, t
                - 5
                - 5
                - 5
            deg: 3
    v2-Re-200:
        ref_params:
            l_ref: 0.1080000
            v_ref: 165.690000
            p_ref: 1.00E+05
        sim_params:
            rho: 0.0011400
            mu: 0.0001020
            g: 981
            dt: 0.000004
        x_range:
            - 120
            - 200
        y_range: 
            - 50
            - 172